site_name: The Landlab-ASPECT Project
site_url:  https://landlab-aspect.github.io
#repo_name: dealii/dealii
#repo_url:  https://github.com/dealii/dealii

plugins: []
nav:
  - Home: index.md
  - about.md
  - people.md
  - blog.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.path
    - header.autohide
    - toc.integrate
    - toc.follow
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  logo:    assets/logo512.png
  favicon: assets/logo128.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  homepage: https://landlab-aspect.github.io
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/landlab-aspect
  generator: false
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2024 by the authors
