authors:
  tjhei:
    name: Timo Heister
    description: Clemson University
    avatar: https://github.com/tjhei.png
    
  danieldouglas92:
    name: Daniel Douglas
    description: Boston College
    avatar: https://github.com/danieldouglas92.png
